name: Auto Assign PR

on:
  pull_request:
    types:
      - opened

jobs:
  assign-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.addAssignees({
              issue_number: context.payload.pull_request.number,
              assignees: [context.payload.pull_request.user.login]
            })
          token: ${{ secrets.GITHUB_TOKEN }}
