name: Auto Assign PR

on:
  pull_request:
    types:
      - opened

jobs:
  assign-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @actions/github octokit/rest.js

      - name: Assign PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const { context, GitHub } = require('@actions/github');
          const octokit = new GitHub(process.env.GITHUB_TOKEN);

          octokit.issues.addAssignees({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            assignees: [context.payload.pull_request.user.login],
          });
