name: Deploy Platform Kit (STAGE)

on:
  push:
    branches:
      - dev
env:
  HUSKY: 0

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: node:18-alpine3.18
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SO deps
        run: apk add curl git bash jq

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Download Azion CLI
        run: curl https://downloads.azion.com/linux/x86_64/azioncli -o azioncli && chmod +x azioncli

      - name: Configure Azion CLI
        run: ./azioncli configure -t ${{ secrets.PLATFORM_KIT_TOKEN }}

      - name: Define application settings
        run: >
          echo $(jq
          --arg name ${{secrets.STAGE_EDGE_APPLICATION_NAME}} 
          --arg funcid ${{secrets.STAGE_EDGE_FUNCTION_ID}} 
          --arg appid ${{secrets.STAGE_EDGE_APPLICATION_ID}} 
          --arg domainid ${{secrets.STAGE_DOMAIN_ID}} 
          '.name = ($name)
          | .function.id = ($funcid|tonumber)
          | .application.id = ($appid|tonumber)
          | .domain.id = ($domainid|tonumber)'
          azion/azion.json) > azion/azion.json

      - name: Configure Repository
        run: mkdir -p .edge/statics && cp -r ./dist/* .edge/statics

      - name: Deploy Edge Application
        run: ./azioncli edge_applications publish
